module.exports = {
    actionAmount: 0,
    turn: 1,
    gamePhase: false,
    turnPhase: false,
    gameStarting: false,
    playerCount: 0,
    arp1: 0,
    arp2: 0,
    p1CharDied: false,
    p2CharDied: false,
    dodgecdMax: 2,
    player1: {},
    player2: {},
};